src/cheri_cap_common.sail
Sail does not permit pattern matching on symbols except for constructors: instead it treats them as fresh variables matching a wildcard expression. That means this match was totally broken and always returned true. The only use of this function is in CJALR and the bug meant it was possible to jump to a capability that is not sealed with a sentry type. We fix this by using guards as suggested by @bacam. Fixes #5 .
=> Fix bad pattern match in isCapSentry.

src/cheri_cap_common.sail
This format is more useful as it shows the address instead of the offset and permissions as letters instead of bits.  Unfortunately it probably slows down tracing quite a lot due to inefficient string concatenation.
=> Print capability values in same format as RTOS.

src/cheri_addr_checks.sail, src/cheri_sys_regs.sail
This adds a mew CSR, MSLWM.
When written this records the base and top of the written capability as the stack bounds and the address as the current stack low water mark. When read only the integer value of the stack low water mark is returned. Stores update the stack low water mark if the address is between the recorded stack bounds and less than the previous water mark.
=> Add stack low water mark.

src/cheri_regs.sail
The ISA doc says that MTCC should be initialised to the executable root. This makes sense as it needs to be executable to be used as the trap vector. Sail was erroneously setting it to the memory RW root, so fix it here. cheriot-rtos never actually uses this initial value: instead it writes MTCC with a PCC derived capability, hence why this was not noticed before. Spotted by @kliuMsft .
=> Fix initialisation of MTCC register.

.github/workflows/compile.yml, src/cheri_insts.sail, src/cheri_types.sail
It's difficult to write defensive code if stores may trap depending on the copied value.  Allowing store-local to trap makes it easy to force anything that copies on behalf of a caller able to trap by inserting a local capability into the source that it's copying from.
This change is already made in CHERIoT Ibex, the spec is catching up.
This also removes the associated exception codes.  We may wish to reserve them for a debugging mode for finding places where the tag clearing occurs.
Fixes #20.
=> Make store-local violations non-trapping.

archdoc/chap-abi.tex, archdoc/chap-changes.tex
This catches the specification up to CHERIoT-Platform/llvm-project#14
=> Update the specification for the newer relocation types.

archdoc/chap-changes.tex, archdoc/chap-cheri-riscv.tex
There was an inconsistency between the Sail implementation and the ISA document about the locations of the T and B fields in the capability encoding.  The document had the T and B fields swapped compared to the Sail (which matches the Ibex implementation) so we treat the Sail as canonical and update the document to match i.e. B is in bits 0 to 8 of the metadata word and T is in 9 to 17. Thanks to @vmurali for spotting this.
Also fix a minor typo in description of R bit.
=> Fix reversed T and B fields in the capability encoding diagram.

archdoc/chap-cheri-riscv.tex
- Spelling mistakes.
- Make sentences start on new line.
- Remove multiple the.
=> Some minor textual changes to the RISC-V chapter

README.md
This add instructions on how to build the architecture specification document to the README file.
=> Add archdoc build instructions

archdoc/chap-changes.tex, archdoc/chap-cheri-riscv.tex, archdoc/chap-compartment-model.tex, archdoc/preamble.tex, src/cheri_addr_checks.sail, src/cheri_sys_regs.sail
Make it explicitly 16-byte aligned and point out the unaligned write spanning mshwmb corner case, which we do not require hardware to handle.
Fixes #15.
=> Document stack high water mark.

Makefile
HINT encodings were added to sail-riscv in:
https://github.com/riscv/sail-riscv/commit/c138a086f91552bc158f3bfab9a52221a0819171 It appears the new "riscv_insts_hints.sail" file this commit creates did not get added to the cheriot-sail Makefile.
Add it now to avoid falsely trapping HINT instruction encodings. Encountered when testing with TestRIG, where a valid RVC HINT was being interpreted as `c.illegal' rather than `c.slli.hint.zero.0xc`.
=> Include HINT encodings in build

.github/workflows/compile.yml
The github version of sail has some fixes we need for latex output. Let's pin CI to this commit until a new sail is released.
Also update version of upoad-artifact action to non-deprecated version.
=> Use dev version of sail from github for CI.

src/cheri_cap_common.sail, src/cheri_insts_begin.sail, src/cheri_mem.sail, src/cheri_mem_metadata.sail, src/cheri_pc_access.sail, src/cheri_prelude.sail, src/cheri_reg_type.sail, src/cheri_regs.sail, src/cheri_step_ext.sail, src/cheri_sys_exceptions.sail
The warning reads:
Explicit effect annotations are deprecated. They are no longer used and can be removed.
I tested this using the upstream Sail compiler: https://github.com/rems-project/sail/tree/b81e2823f8b4ffcf14cb0b11c260d79d3a19b0dc
=> This avoids a deprecations warning from Sail

archdoc/chap-changes.tex, archdoc/chap-cheri-riscv.tex, src/cheri_insts.sail
Backwards control-flow arcs should ideally be confined to the stack and register save areas.  Conveniently, we have mechanism in the RTOS to identify exactly those areas of memory, with capabilities bearing `SL` (store local) permission. And, after https://github.com/microsoft/cheriot-sail/pull/54, the ISA has mechanism for identifying backwards control-flow arcs, with the two return sentry types.  We should have capability store impose the requirement for `SL` in the authorizing cap if the cap being stored is a return sentry.
Credit where it's due: this is Robert's idea, originally suggested in my obviously-wrong-in-retrospect
https://github.com/microsoft/cheriot-sail/issues/63 ("Have CJALR create !G sentries?").
=> Require store local when storing return sentries

src/cheri_insts.sail
Previously we had otype 4 and 5 being reserved and CSeal can't seal to those types (will clear tag). With PR#54, 4 and 5 are now defined as backward sentries so it seems logical to allow CSeal to create those otypes.
=> Allowing CSeal to set otype to any value between 0 and 7 for EX capabilities

Makefile
And sail has binary releases, so it may not be installed in a way opam understands.  Therefore, apply the relevant hunk from https://github.com/riscv/sail-riscv/pull/532 so that we just ask the `sail` that we find on the `$PATH` where it was installed, rather than asking opam.
=> Makefile: sail can report its library path

archdoc/cheriot-architecture.tex
Enough things in 0.6 are his fault that he shouldn't be allowed to escape blame.
=> Blame Murali for stuff.

src/cheri_addr_checks.sail, src/cheri_cap_common.sail
While here, speed up compilation so future work isn't as painful.
=> Detect and abort if trapping with untagged MTCC.

archdoc/chap-changes.tex, archdoc/chap-cheri-riscv.tex, src/cheri_insts.sail
It was not fully baked on the way in and probably merits a bit more thought before we commit to it.
=> Remove reverse sentry pseudolocality

archdoc/chap-changes.tex, src/cheri_insts.sail
FIXES https://github.com/CHERIoT-Platform/cheriot-sail/issues/71
=> CUnseal: permit any in-bound type

Makefile, archdoc/app-isaquick-riscv.tex, archdoc/chap-changes.tex, archdoc/chap-encoding-sail.tex, archdoc/chap-isaref-riscv.tex, archdoc/def-riscv-insns.tex, archdoc/insn-riscv/csetboundsrounddown.tex, properties/Makefile, properties/proplib.sail, properties/props.sail, properties/props_setboundsrounddown.sail, src/cheri_cap_common.sail, src/cheri_insts.sail
=> CSetBoundsRoundDown

archdoc/chap-changes.tex, archdoc/chap-encoding-sail.tex, properties/props.sail, src/cheri_insts.sail
Address #70.  This is not ready to merge, in that it hasn't yet decided between the two options:
1. Require that the mask to `CAndPerms` on a sealed operand _must_ be all-ones or all-ones-but-`GL`
2. Require only that the _difference_ between the initial and masked permissions be at most the `GL` bit.
Shuffle the comment delimiters around to pick between the two.  I believe either is fine from a security perspective; option 1 imposes stronger requirements on the program(mer) while the later tolerates some... incidental correctness.  If one is clearly better for microarchitecture, tho', that could be the deciding factor.
Pinging @kliuMsft.
=> CAndPerms: permit clearing GL on sealed caps

archdoc/chap-changes.tex, archdoc/chap-cheri-riscv.tex, src/cheri_insts.sail
Attempt at capturing https://github.com/CHERIoT-Platform/cheriot-sail/issues/85
=> Proposed relaxing of cjalr sealing

src/cheri_insts.sail
Sigh, sorry.  This was originally "~(mask | perm_global) == zeros()" and had one too many inversions applied.
=> candperm: brown paper bag fix for #83
